<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PSP.TopupService.ArchitectureTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NetArchTest.eNhancedEdition" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PSP.TopupService.SharedKernel\PSP.TopupService.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\PSP.TopupService.Domain\PSP.TopupService.Domain.csproj" />
    <ProjectReference Include="..\..\src\PSP.TopupService.Contracts\PSP.TopupService.Contracts.csproj" />
    <ProjectReference Include="..\..\src\PSP.TopupService.Application\PSP.TopupService.Application.csproj" />
    <ProjectReference Include="..\..\src\PSP.TopupService.Infrastructure\PSP.TopupService.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\PSP.TopupService.Persistence\PSP.TopupService.Persistence.csproj" />
    <ProjectReference Include="..\..\src\PSP.TopupService.Api\PSP.TopupService.Api.csproj" />
    <ProjectReference Include="..\..\src\PSP.TopupService.Worker\PSP.TopupService.Worker.csproj" />
  </ItemGroup>

</Project>
