<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>PSP.Mock.HamrahAval.Api</RootNamespace>
    <Description>Hamrah-e-Aval (MCI) simulator with configurable failure rate, timeout and delay.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PSP.TopupService.Contracts\PSP.TopupService.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" />
  </ItemGroup>

</Project>
