<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PSP.TopupService.Domain</RootNamespace>
    <Description>Rich domain model: Topup aggregate, entities, value objects, domain events and domain exceptions.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PSP.TopupService.SharedKernel\PSP.TopupService.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" />
  </ItemGroup>

</Project>
