<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PSP.TopupService.Infrastructure</RootNamespace>
    <Description>Infrastructure: external clients (Bank, Hamrah-e-Aval), messaging adapters, Polly resilience.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PSP.TopupService.Application\PSP.TopupService.Application.csproj" />
    <ProjectReference Include="..\PSP.TopupService.Domain\PSP.TopupService.Domain.csproj" />
    <ProjectReference Include="..\PSP.TopupService.Contracts\PSP.TopupService.Contracts.csproj" />
    <ProjectReference Include="..\PSP.TopupService.SharedKernel\PSP.TopupService.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Polly" />
    <PackageReference Include="StyleCop.Analyzers" PrivateAssets="all" />
  </ItemGroup>

</Project>
