// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PSP.TopupService.Persistence.Context;

#nullable disable

namespace PSP.TopupService.Persistence.Migrations
{
    [DbContext(typeof(TopupDbContext))]
    partial class TopupDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PSP.TopupService.Domain.Topups.TopupTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("failure_message");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_topup_transactions");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_topup_transactions_correlation_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_topup_transactions_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_topup_transactions_status");

                    b.HasIndex("IsDeleted", "CreatedOnUtc")
                        .HasDatabaseName("ix_topup_transactions_is_deleted_created_on_utc");

                    b.ToTable("topup_transactions", (string)null);
                });

            modelBuilder.Entity("PSP.TopupService.Persistence.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor");

                    b.Property<string>("AfterState")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_state");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("RemoteIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("remote_ip");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("TopupId")
                        .HasColumnType("uuid")
                        .HasColumnName("topup_id");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation_id");

                    b.HasIndex("TopupId", "OccurredOnUtc")
                        .HasDatabaseName("ix_audit_logs_topup_id_occurred_on_utc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("PSP.TopupService.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("id");

                    b.Property<string>("Consumer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("consumer");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTime>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("MessageId", "Consumer")
                        .IsUnique()
                        .HasDatabaseName("ix_inbox_messages_message_id_consumer");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("PSP.TopupService.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime?>("DeadLetterAfterUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_letter_after_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("routing_key");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbox_messages_correlation_id");

                    b.HasIndex("Status", "OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_status_occurred_on_utc")
                        .HasFilter("status = 0");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("PSP.TopupService.Domain.Topups.TopupTransaction", b =>
                {
                    b.OwnsOne("PSP.TopupService.Domain.Topups.Entities.ReverseRecord", "Reverse", b1 =>
                        {
                            b1.Property<Guid>("TopupId")
                                .HasColumnType("uuid")
                                .HasColumnName("topup_id");

                            b1.Property<DateTime?>("CompletedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at_utc");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on_utc");

                            b1.Property<DateTime?>("DeletedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_on_utc");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("InitiatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("initiated_at_utc");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("is_deleted");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("text")
                                .HasColumnName("modified_by");

                            b1.Property<DateTime>("ModifiedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("modified_on_utc");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(48)
                                .HasColumnType("character varying(48)")
                                .HasColumnName("reason");

                            b1.Property<string>("RequestedBy")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("requested_by");

                            b1.Property<byte[]>("RowVersion")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("row_version");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("status");

                            b1.HasKey("TopupId")
                                .HasName("pk_topup_reversals");

                            b1.ToTable("topup_reversals", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TopupId")
                                .HasConstraintName("fk_topup_reversals_topup_transactions_topup_id");

                            b1.OwnsOne("PSP.TopupService.Domain.Topups.ValueObjects.TransactionReference", "BankReversalReference", b2 =>
                                {
                                    b2.Property<Guid>("ReverseRecordTopupId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("topup_id");

                                    b2.Property<string>("Source")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("character varying(32)")
                                        .HasColumnName("bank_reversal_reference_source");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("bank_reversal_reference_value");

                                    b2.HasKey("ReverseRecordTopupId")
                                        .HasName("pk_topup_reversals");

                                    b2.ToTable("topup_reversals");

                                    b2.WithOwner()
                                        .HasForeignKey("ReverseRecordTopupId")
                                        .HasConstraintName("fk_topup_reversals_topup_reversals_topup_id");
                                });

                            b1.Navigation("BankReversalReference");
                        });

                    b.OwnsMany("PSP.TopupService.Domain.Topups.Entities.TopupAttempt", "Attempts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("AttemptNumber")
                                .HasColumnType("integer")
                                .HasColumnName("attempt_number");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("text")
                                .HasColumnName("created_by");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on_utc");

                            b1.Property<DateTime?>("DeletedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deleted_on_utc");

                            b1.Property<string>("ErrorMessage")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("error_message");

                            b1.Property<DateTime?>("FinishedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("finished_at_utc");

                            b1.Property<int?>("HttpStatusCode")
                                .HasColumnType("integer")
                                .HasColumnName("http_status_code");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean")
                                .HasColumnName("is_deleted");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("text")
                                .HasColumnName("modified_by");

                            b1.Property<DateTime>("ModifiedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("modified_on_utc");

                            b1.Property<string>("ProviderReference")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("provider_reference");

                            b1.Property<byte[]>("RowVersion")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("row_version");

                            b1.Property<DateTime>("StartedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("started_at_utc");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("status");

                            b1.Property<Guid>("TopupId")
                                .HasColumnType("uuid")
                                .HasColumnName("topup_id");

                            b1.HasKey("Id")
                                .HasName("pk_topup_attempts");

                            b1.HasIndex("TopupId", "AttemptNumber")
                                .IsUnique()
                                .HasDatabaseName("ix_topup_attempts_topup_id_attempt_number");

                            b1.ToTable("topup_attempts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TopupId")
                                .HasConstraintName("fk_topup_attempts_topup_transactions_topup_id");
                        });

                    b.OwnsOne("PSP.TopupService.Domain.Topups.ValueObjects.TransactionReference", "BankReference", b1 =>
                        {
                            b1.Property<Guid>("TopupTransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("bank_reference_source");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("bank_reference_value");

                            b1.HasKey("TopupTransactionId");

                            b1.ToTable("topup_transactions");

                            b1.WithOwner()
                                .HasForeignKey("TopupTransactionId")
                                .HasConstraintName("fk_topup_transactions_topup_transactions_id");
                        });

                    b.OwnsOne("PSP.TopupService.Domain.Topups.ValueObjects.TransactionReference", "MciReference", b1 =>
                        {
                            b1.Property<Guid>("TopupTransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("mci_reference_source");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("mci_reference_value");

                            b1.HasKey("TopupTransactionId");

                            b1.ToTable("topup_transactions");

                            b1.WithOwner()
                                .HasForeignKey("TopupTransactionId")
                                .HasConstraintName("fk_topup_transactions_topup_transactions_id");
                        });

                    b.OwnsOne("PSP.TopupService.Domain.Topups.ValueObjects.MobileNumber", "MobileNumber", b1 =>
                        {
                            b1.Property<Guid>("TopupTransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("mobile_number");

                            b1.HasKey("TopupTransactionId");

                            b1.ToTable("topup_transactions");

                            b1.WithOwner()
                                .HasForeignKey("TopupTransactionId")
                                .HasConstraintName("fk_topup_transactions_topup_transactions_id");
                        });

                    b.OwnsOne("PSP.TopupService.Domain.Topups.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TopupTransactionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.HasKey("TopupTransactionId");

                            b1.ToTable("topup_transactions");

                            b1.WithOwner()
                                .HasForeignKey("TopupTransactionId")
                                .HasConstraintName("fk_topup_transactions_topup_transactions_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Attempts");

                    b.Navigation("BankReference");

                    b.Navigation("MciReference");

                    b.Navigation("MobileNumber")
                        .IsRequired();

                    b.Navigation("Reverse");
                });
#pragma warning restore 612, 618
        }
    }
}
